### Register User - Complete Profile
POST http://localhost:5000/api/main/register
Content-Type: application/json

{
    "name": "Tummala Naveen",
    "email": "naveentummala033@gmail.com",
    "password": "Sevaksha@2025",
    "mobile": "9876543210",
    "age": 25,
    "income": 350000.00,
    "occupation": "Student",
    "gender": "Male",
    "marital_status": "Never Married"
}

### Register User - Minimal Profile
POST http://localhost:5000/api/main/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "testuser@gmail.com",
    "password": "Test@2025",
    "mobile": "9876543211"
}

### Login with Email
POST http://localhost:5000/api/main/login
Content-Type: application/json

{
    "identifier": "naveentummala033@gmail.com",
    "password": "Sevaksha@2025"
}

### Login with Mobile
POST http://localhost:5000/api/main/login
Content-Type: application/json

{
    "identifier": "9876543210",
    "password": "Sevaksha@2025"
}

### Get All Schemes
GET https://7a79-103-248-208-101.ngrok-free.app/api/main/schemes

### Get All Schemes by Category
POST http://localhost:5000/api/main/search
Content-Type: application/json

{
    "search_term": "Widow"
}