### Create User
POST http://localhost:5000/api/main/register
Content-Type: application/json

{
    "name": "Library User",
    "username": "library_user",
    "email": "naveentummala2308@gmail.com",
    "password": "LibraryUser@2024"
}

### Login Librarian
POST http://localhost:5000/api/main/login
Content-Type: application/json

{
    "username": "library_admin",
    "password": "LibraryAdmin@2024",
    "role": "librarian"
}

### Login User
POST http://localhost:5000/api/main/login
Content-Type: application/json

{
    "username": "library_user",
    "password": "LibraryUser@2024"
}

### Get All Schemes
GET https://7a79-103-248-208-101.ngrok-free.app/api/main/schemes